### PR TITLE
Move website deployment out of Rust CI

### PR DESCRIPTION
**Pull request by tolikzinovyev**
## Content

The website stuff shouldn't be part of Rust CI. Also, the skipped docs check that never runs on pull requests is a bit annoying.

Screenshot 2024-11-18 at 23-10-37 Design document by tolikzinovyev · Pull Request #67 · cardano-scaling_alba

### CODE REVIEW

**Comment by rrtoledo** [comment]
Which issue is this PR linked to?

**Review by rrtoledo — CHANGES_REQUESTED** [review]
While we should not care about deploying the website on the CI, we definitely should build cargo doc to make sure that the documentation can be built and the examples do not fail (that would be embarassing).
If it is not the case (I haven't checked), I would like to add it in this PR (as you already talk about skipped doc in the CI).

Also can you write an issue to attach to this PR?

**Review by curiecrypt — APPROVED** [review]
LGTM
After linking it to an issue, it can be merged. 
I will take care of building the cargo doc, issue #74. @rrtoledo

**Comment by tolikzinovyev** [comment]
I'm not sure we need an issue for such small changes. We don't want to introduce friction for improving the codebase. What do you think?

**Review by rrtoledo — APPROVED** [review]

**Pull request merged**
