### PR TITLE
Add wrapper structure to work on

### PR DESCRIPTION
**Pull request by rrtoledo**
## Content

Restructure the code to have a user facing structure from which we can directly prove and verify.

## Pre-submit checklist

- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
- PR
    - [x] No clippy warnings in the CI
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested
- Documentation
    - [x] Update README file (if relevant)
    - [x] Update documentation website (if relevant)

## Comments

I removed the Params structure as it was not really needed and renamed the Setup one "Params".
I moved back the code into impls so that it is easier to use generics.

## Issue(s)

Relates to #59

### CODE REVIEW

**Comment by rrtoledo** [comment]
I used "telescope" as name for the wrapper structure, I am more than happy to change this.

**Comment by rrtoledo** [comment]
@djetchev @curiecrypt Are the comments for public functions reasonable? They could be more verbose perhaps?

**Review by tolikzinovyev — CHANGES_REQUESTED** [review]
I'm not a big fan of the interface of `Telescope::new()`. This will just encourage the user to use user-friendly parameters instead of hardcoding `Setup`, which goes against https://github.com/cardano-scaling/alba/blob/8d8bcbfb130c58d57e7b6148c74737c35babc835/design/design.md#parameter-calculation.

I think `new()` should accept `Setup` only.

**Comment by rrtoledo** [comment]
> I'm not a big fan of the interface of `Telescope::new()`. This will just encourage the user to use user-friendly parameters instead of hardcoding `Setup`, which goes against https://github.com/cardano-scaling/alba/blob/8d8bcbfb130c58d57e7b6148c74737c35babc835/design/design.md#parameter-calculation.
> 
> I think `new()` should accept `Setup` only.

And I strongly disagree with you. We should not make giving hardcoded parameters the norm, as we have no insurance they were computed correctly, this should also go against usable security.

**Review by curiecrypt — DISMISSED** [review]
I am OK with this wrapper structure. It seems professional, user-friendly, and easy to read.
I just have 2 minor comments.
LGTM 👍

**Comment by curiecrypt** [comment]
> I used "telescope" as name for the wrapper structure, I am more than happy to change this.

I tried to put another name but couldn't find a better one. We might think of a more creative one in the future.

**Comment by tolikzinovyev** [comment]
I see your point @curiecrypt. More importantly, I think, we need to be coherent as a team. A design decision should first be discussed on the design document _before_ there is a pull request that contradicts it. Otherwise, what is the point of the design document?

**Comment by rrtoledo** [comment]
Replaced by https://github.com/cardano-scaling/alba/pull/116

**Pull request closed without merging**
